"""Add primary key column

Revision ID: e89747410997
Revises: 
Create Date: 2023-11-11 15:10:38.692216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import create_engine, MetaData, Table, Column, Integer

# revision identifiers, used by Alembic.
revision = 'e89747410997'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_orignal')
    with op.batch_alter_table('db_messy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('YEAR', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('HOST', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('CHAMPION', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('RUNNER_UP', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('THIRD_PLACE', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('MATCHES_PLAYED', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('GOALS_SCORED', sa.Integer(), nullable=True))
        batch_op.drop_column('Matches Played')
        batch_op.drop_column('Third Place')
        batch_op.drop_column('Year')
        batch_op.drop_column('Host')
        batch_op.drop_column('Runner Up')
        batch_op.drop_column('Goals Scored')
        batch_op.drop_column('Champion')
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_messy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Champion', mysql.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('Goals Scored', mysql.VARCHAR(length=12), nullable=True))
        batch_op.add_column(sa.Column('Runner Up', mysql.VARCHAR(length=14), nullable=True))
        batch_op.add_column(sa.Column('Host', mysql.VARCHAR(length=18), nullable=True))
        batch_op.add_column(sa.Column('Year', mysql.VARCHAR(length=4), nullable=True))
        batch_op.add_column(sa.Column('Third Place', mysql.VARCHAR(length=13), nullable=True))
        batch_op.add_column(sa.Column('Matches Played', mysql.VARCHAR(length=14), nullable=True))
        batch_op.drop_column('GOALS_SCORED')
        batch_op.drop_column('MATCHES_PLAYED')
        batch_op.drop_column('THIRD_PLACE')
        batch_op.drop_column('RUNNER_UP')
        batch_op.drop_column('CHAMPION')
        batch_op.drop_column('HOST')
        batch_op.drop_column('YEAR')

    op.create_table('db_orignal',
    sa.Column('COL 1', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('COL 2', mysql.VARCHAR(length=18), nullable=True),
    sa.Column('COL 3', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('COL 4', mysql.VARCHAR(length=14), nullable=True),
    sa.Column('COL 5', mysql.VARCHAR(length=13), nullable=True),
    sa.Column('COL 6', mysql.VARCHAR(length=14), nullable=True),
    sa.Column('COL 7', mysql.VARCHAR(length=12), nullable=True),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
